services:
  db:
    image: postgres:16-alpine
    container_name: eatmeat-postgres
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eatmeat
    volumes:
      - eatmeat_pgdata:/var/lib/postgresql/data

volumes:
  eatmeat_pgdata:
